settings:
  network:
    port: 3005
  database:
    uri: "postgres://"
    auto_migration: false
  redis:
    uri: "redis://"
    ssl: true
  cache:
    enabled: true
    ttl: 3600
  rate_limiting:
    enabled: true
    max: 100
    window: 60
    expiration: 60
  audit_logging:
    enabled: false
  usage_logging:
    enabled: false
  rule_server:
    url: "http://localhost:8080"

providers:
  openai:
    enabled: true
  huggingface:
    enabled: true


rules:
  input:
    - name: "language_detection"
      type: "language_detection"
      enabled: false
      action:
        type: "block" # blocking and logging
    - name: "pii_example"
      type: "pii_filter"
      enabled: false
      config:
        model_name: "value1"
        model_url: "value2"
        model_type: ""
      action:
        type: "block" # blocking and logging
    #      - type: "mask" # masking and logging
    #      - type: "monitoring" # logging

    - name: "prompt_injection_example"
      type: "prompt_injection"
      enabled: true
      config:
        plugin_name: "prompt_injection_llm"
        threshold: 0.85
      action:
        type: "block"
  #      - type: "monitoring" # logging
  output:
    - name: "pii_example"
      type: "pii_filter"
      config:
        model_name: "value1"
        model_url: "value2"
        model_type: ""
      action:
        type: "block"