name: Shared Steps
description: 'Shared steps for freeing disk space'
runs:
  using: "composite"
  steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: false
        dotnet: false
        haskell: false
        large-packages: false
        docker-images: false
        swap-storage: false