name: cache-preview

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - services/cache/**
      - .github/workflows/cache-preview.yaml
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  image-build:
    runs-on: ubicloud-standard-2
    if: |
      (github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, 'test') &&
      github.event.issue.pull_request != null &&
      github.event.pull_request.changed_files > 0) ||
      (github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved' &&
      github.event.pull_request.changed_files > 0)
    steps:
      - name: Check for path changes
        id: path-check
        run: |
          echo "Checking for changes in specified paths..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'services/cache/|.github/workflows/cache-pull.yaml' || echo "no-changes"

      - name: Login to Github Packages
        if: steps.path-check.outputs.result != 'no-changes'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.path-check.outputs.result != 'no-changes'
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: 🏗 Setup repo
        if: steps.path-check.outputs.result != 'no-changes'
        uses: actions/checkout@v4

      - name: Set up Docker Context for Buildx
        if: steps.path-check.outputs.result != 'no-changes'
        run: docker context create builders

      - name: Set up Docker Buildx
        if: steps.path-check.outputs.result != 'no-changes'
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        if: steps.path-check.outputs.result != 'no-changes'
        id: cache
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openshieldai/openshield/cache
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build
        if: steps.path-check.outputs.result != 'no-changes'
        uses: docker/build-push-action@v6
        with:
          context: services/cache
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ${{ steps.cache.outputs.tags }}
          labels: ${{ steps.cache.outputs.labels }}
