name: core-unit-test

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - .github/workflows/core-pull.yaml

jobs:
  core-unit-test:
    name: Core unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23' ]
    steps:
      - uses: actions/checkout@v4

      - name: Copy and rename config file
        run: cp config_example.yaml config.yaml

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get -v

      - name: Run unit tests
        run: ENV=test go test ./...


  core-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: Set up Docker Context for Buildx
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        id: openshield
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openshieldai/openshield/openshield
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.api.outputs.tags }}
          labels: ${{ steps.api.outputs.labels }}
