name: Core Service Preview

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - .github/workflows/core-preview.yaml
  pull_request_review:
    types: [submitted]

jobs:
  core-unit-test:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    name: Core unit tests
    runs-on: ubicloud-standard-2
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23' ]
    steps:
      - uses: actions/checkout@v4

      - name: Check for path changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - '*.go'
              - 'go.mod'
              - 'go.sum'
              - '.github/workflows/core-preview.yaml'

      - name: Copy and rename config file
        if: steps.changes.outputs.core == 'true'
        run: cp config_example.yaml config.yaml

      - name: Setup Go ${{ matrix.go-version }}
        if: steps.changes.outputs.core == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        if: steps.changes.outputs.core == 'true'
        run: go get -v

      - name: Run unit tests
        if: steps.changes.outputs.core == 'true'
        run: ENV=test go test ./...

  core-docker-build:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@v4

      - name: Check for path changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - '*.go'
              - 'go.mod'
              - 'go.sum'
              - '.github/workflows/core-preview.yaml'

      - name: Login to Github Packages
        if: steps.changes.outputs.core == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.changes.outputs.core == 'true'
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Context for Buildx
        if: steps.changes.outputs.core == 'true'
        run: docker context create builders

      - name: Set up Docker Buildx
        if: steps.changes.outputs.core == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        if: steps.changes.outputs.core == 'true'
        id: cache
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openshieldai/openshield/cache
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build
        if: steps.changes.outputs.core == 'true'
        uses: docker/build-push-action@v6
        with:
          context: services/cache
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ${{ steps.cache.outputs.tags }}
          labels: ${{ steps.cache.outputs.labels }}
