name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  core-release:
    runs-on: ubicloud-standard-2
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: Set up Docker Context for Buildx
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        id: openshield
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openshieldai/openshield/openshield
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.openshield.outputs.tags }}
          labels: ${{ steps.openshield.outputs.labels }}

  rule-release:
    runs-on: ubicloud-standard-2
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: Set up Docker Context for Buildx
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        id: rule
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openshieldai/openshield/rule
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: services/rule
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.rule.outputs.tags }}
          labels: ${{ steps.rule.outputs.labels }}

  cache-release:
    runs-on: ubicloud-standard-2
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: Set up Docker Context for Buildx
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        id: cache
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openshieldai/openshield/cache
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: services/cache
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.cache.outputs.tags }}
          labels: ${{ steps.cache.outputs.labels }}
